import math

# RS Parameters

SYMB_WIDTH = 8
SYMB_NUM = 2 ** SYMB_WIDTH
BUS_WIDTH_IN_SYMB = 4

if(SYMB_WIDTH == 8):
    POLY = 285
    N_LEN = 255
    K_LEN = 239
elif(SYMB_WIDTH == 7):
    POLY = 137
elif(SYMB_WIDTH == 6):
    POLY = 67
elif(SYMB_WIDTH == 5):
    POLY = 37
elif(SYMB_WIDTH == 4):
    POLY = 19
elif(SYMB_WIDTH == 3):
    POLY = 11
elif(SYMB_WIDTH == 2):
    POLY = 7

BLOCK_CYCLES = int(math.ceil(N_LEN/BUS_WIDTH_IN_SYMB))
ROOTS_NUM = N_LEN-K_LEN
T_LEN = math.floor(ROOTS_NUM/2)

CHIEN__ROOTS_NUM = SYMB_NUM - 2

CHIEN__ROOTS_PER_CYCLE = 16
if(CHIEN__ROOTS_NUM % CHIEN__ROOTS_PER_CYCLE):
    CHIEN__CYCLES_NUM = int(CHIEN__ROOTS_NUM % CHIEN__ROOTS_PER_CYCLE)+1
else:
    CHIEN__CYCLES_NUM = int(CHIEN__ROOTS_NUM % CHIEN__ROOTS_PER_CYCLE)
    
ROOTS_PER_CYCLE__CHIEN_BYTES = int(CHIEN__ROOTS_PER_CYCLE / 8)
